apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "scraper-worker.fullname" . }}
  labels:
{{ include "scraper-worker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scraper-worker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scraper-worker.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATA_SERVICE_URL
              value: {{ .Values.env.DATA_SERVICE_URL }}
            - name: SCRAPER_SERVICE_URL
              value: {{ .Values.env.SCRAPER_SERVICE_URL }}
            - name: WORKER_MANAGER_URL
              value: {{ .Values.env.WORKER_MANAGER_URL }}

            - name: RUN_TASK_QUEUE_NAME
              value: {{ .Values.env.RUN_TASK_QUEUE_NAME }}
            - name: INBOX_QUEUE_NAME
              value: {{ .Values.env.INBOX_QUEUE_NAME }}

            - name: INBOX_FANOUT_EXCHANGE_NAME
              value: {{ .Values.env.INBOX_FANOUT_EXCHANGE_NAME }}
            - name: RUN_TASK_EXCHANGE_NAME
              value: {{ .Values.env.RUN_TASK_EXCHANGE_NAME }}

            - name: RUN_TASK_ROUTING_KEY
              value: {{ .Values.env.RUN_TASK_ROUTING_KEY }}

            - name: WORKER_TYPE
              value: {{ .Values.env.WORKER_TYPE }}
            - name: CONTAINER_KEY
              value: {{ .Values.env.CONTAINER_KEY }}

            - name: AMQP_CONNECTION_STRING
              value: {{ .Values.env.AMQP_CONNECTION_STRING }}
            - name: AMQP_LOG_LEVEL
              value: {{ .Values.env.AMQP_LOG_LEVEL }}

            - name: MAX_CHROME_TABS
              value: {{ .Values.env.MAX_CHROME_TABS | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
