apiVersion: v1
kind: Service
metadata:
  name: {{ template "scraper-worker.fullname" . }}
  labels:
{{ include "scraper-worker.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http2
  selector:
    app.kubernetes.io/name: {{ include "scraper-worker.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
