# Default values for scraper-worker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: localhost:32000/scraper-worker
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: app.elasticdata.io

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

env:
  USE_ISOLATION_MODE: 0
  PUPPETEER_HEADLESS: 1

  GLOBAL_PREFIX: worker
  DATA_SERVICE_URL: http://localhost:3000/worker
  SCRAPER_SERVICE_URL: http://backend:8080
  WORKER_MANAGER_URL: http://localhost:3005

  RUN_TASK_QUEUE_NAME: PROD_TASK_RUN
  INBOX_QUEUE_NAME: PROD_WORKER_INBOX

  INBOX_FANOUT_EXCHANGE_NAME: PROD_INBOX_FANOUT
  RUN_TASK_EXCHANGE_NAME: PROD_RUN_TASK

  RUN_TASK_ROUTING_KEY: PROD_RUN_TASK

  WORKER_TYPE: SHARED
  FROM_CONTAINER_KEY: FROM_CONTAINER_KEY

  AMQP_CONNECTION_STRING: amqp://user:password@rabbitmq.rabbitmq:5672
  AMQP_LOG_LEVEL: info

  MAX_CHROME_TABS: 3

  APP_MINIO_ACCESS_KEY: elasticdataio
  APP_MINIO_SECRET_KEY: wJalrXUtnFEMI/9874c97c907209cpuvpw97bpb/asdasdasdasdasd
  APP_MINIO_END_POINT: minio
  APP_MINIO_PORT: 9000
  APP_MINIO_USE_SSL: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 700m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
