version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13.8
    labels:
      worker: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5454:5432"
    networks:
      - worker
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  worker:
    driver: bridge

volumes:
  postgres:
    driver: local
