export enum UserInteractionEvent {
  UPDATE_USER_INTERACTION_MODE = 'UPDATE_USER_INTERACTION_MODE',
  DISABLE_USER_INTERACTION_MODE = 'DISABLE_USER_INTERACTION_MODE',
  EXECUTE_CMD = 'EXECUTE_CMD',
}
